# Generated by Django 2.2.14 on 2020-09-29 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='items',
            new_name='item',
        ),
    ]
