# Generated by Django 2.2.14 on 2020-10-20 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_item_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Men'), ('F', 'Women')], max_length=1, null=True),
        ),
    ]
