# Generated by Django 2.2.14 on 2020-12-24 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_item_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['title']},
        ),
        migrations.RemoveField(
            model_name='item',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='quantity',
        ),
        migrations.AddField(
            model_name='item',
            name='city',
            field=models.CharField(choices=[('M', 'Mumbai'), ('D', 'Delhi'), ('C', 'Chennai'), ('H', 'Hyderabad'), ('B', 'Bangalore')], default='D', max_length=1),
        ),
        migrations.AddField(
            model_name='item',
            name='wifi',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='days',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='guest',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('3', '3 Star Hotel'), ('4', '4 Star Hotel'), ('5', '5 Star Hotel')], max_length=2),
        ),
    ]
