# Generated by Django 2.2.14 on 2020-10-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20201021_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Shirt'), ('SW', 'Sport wear'), ('J', 'Jeans'), ('T', 'Tops'), ('D', 'Dresses')], max_length=2),
        ),
    ]
