# Generated by Django 2.2.14 on 2020-12-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20201021_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='star',
            field=models.IntegerField(default=3),
        ),
    ]
