# Generated by Django 2.2.14 on 2020-12-08 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_item_star'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='item',
            name='star',
        ),
        migrations.AddField(
            model_name='item',
            name='wifi',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('3', '3 Star Hotel'), ('4', '4 Star Hotel'), ('5', '5 Star Hotel')], max_length=2),
        ),
    ]
