# Generated by Django 2.2.14 on 2020-12-24 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20201208_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='city',
            field=models.CharField(choices=[('M', 'Mumbai'), ('D', 'Delhi'), ('C', 'Chennai'), ('H', 'Hyderabad'), ('B', 'Bangalore')], default='D', max_length=1),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
